#CREATE DATABASE

CREATE DATABASE TEMP1;

#DELETE DATABASE

DROP DATABASE TEMP1;

#FOR CREATING TABLE OR SEEING DATA AND CHANGES IN DATA AND STORING ANYTHING WE USE (USE METHOD)

CREATE DATABASE COLLEGE;

USE COLLEGE;