CREATE DATABASE IF NOT EXISTS xyz;
USE xyz;

CREATE TABLE employe (
id INT PRIMARY KEY,
name VARCHAR(50),
salary INT NOT NULL
);

INSERT INTO employe VALUE (123, "RATNESH", 150000);
INSERT INTO employe VALUE (124, "RAM", 15000);
INSERT INTO employe VALUE (125, "PRAKASH", 15005);

SELECT * FROM employe;